# Production Environment Configuration for QuantumRerank
# Optimized for production deployment with strict security and performance

# Quantum Engine Configuration
quantum:
  n_qubits: 4
  backend: "default"
  shots: 1024
  optimization_level: 3
  performance_optimized: true
  caching_enabled: true
  error_mitigation: true
  circuit_compilation_level: 2
  
  # Production quantum settings
  enable_noise_simulation: false
  hardware_efficient_ansatz: true
  parameter_binding_optimization: true

# API Configuration
api:
  host: "0.0.0.0"
  port: 8000
  workers: 4
  worker_class: "uvicorn.workers.UvicornWorker"
  max_connections: 1000
  timeout_seconds: 30
  keepalive: 5
  backlog: 2048
  
  # Production API settings
  debug: false
  reload: false
  access_log: true
  use_colors: false
  
  # Rate limiting configuration
  rate_limiting:
    enabled: true
    strict_mode: true
    requests_per_minute: 1000
    requests_per_hour: 50000
    burst_size: 100
    cleanup_interval: 300

# Security Configuration
security:
  authentication_required: true
  rate_limiting_strict: true
  https_only: true
  security_headers: true
  cors_strict: true
  input_validation_strict: true
  
  # Security headers
  headers:
    x_content_type_options: "nosniff"
    x_frame_options: "DENY"
    x_xss_protection: "1; mode=block"
    strict_transport_security: "max-age=31536000; includeSubDomains"
    referrer_policy: "strict-origin-when-cross-origin"
    content_security_policy: "default-src 'self'"
  
  # CORS configuration
  cors:
    allow_origins: 
      - "https://quantumrerank.com"
      - "https://app.quantumrerank.com"
    allow_methods: ["GET", "POST", "PUT", "DELETE", "OPTIONS"]
    allow_headers: ["Content-Type", "Authorization", "X-API-Key"]
    max_age: 3600
    allow_credentials: false

# Monitoring and Observability
monitoring:
  enabled: true
  metrics_endpoint: true
  health_checks: comprehensive
  detailed_logging: true
  
  # Prometheus configuration
  prometheus:
    enabled: true
    port: 8001
    path: "/metrics"
    registry_type: "CollectorRegistry"
    push_gateway: false
  
  # OpenTelemetry configuration
  opentelemetry:
    enabled: true
    service_name: "quantum-rerank-api"
    service_version: "1.0.0"
    environment: "production"
    
    # Tracing configuration
    tracing:
      enabled: true
      sample_rate: 0.1  # 10% sampling for production
      max_spans: 1000
    
    # Metrics configuration
    metrics:
      enabled: true
      export_interval: 30
      max_export_batch_size: 512

# Logging Configuration
logging:
  level: "INFO"
  format: "json"
  structured: true
  include_timestamp: true
  include_caller: true
  
  # Log rotation
  rotation:
    enabled: true
    max_size: "100MB"
    max_files: 10
    max_age: 30  # days
  
  # Log destinations
  destinations:
    console: true
    file: true
    syslog: false
    remote: true
  
  # Sensitive data filtering
  sensitive_fields:
    - "password"
    - "api_key"
    - "token"
    - "secret"

# Caching Configuration
cache:
  enabled: true
  ttl_seconds: 7200  # 2 hours
  max_size: 1000
  cleanup_interval: 300
  
  # Redis configuration (if using)
  redis:
    enabled: true
    host: "redis"
    port: 6379
    db: 0
    max_connections: 100
    connection_timeout: 5
    
  # Memory cache configuration
  memory:
    enabled: true
    max_size_mb: 512
    eviction_policy: "LRU"

# Performance Configuration
performance:
  # PRD target compliance
  targets:
    similarity_computation_ms: 100
    batch_processing_ms: 500
    memory_usage_gb: 2.0
    accuracy_improvement_percent: 15.0
    response_time_ms: 200
    error_rate: 0.01
    uptime: 0.999
  
  # Optimization settings
  optimization:
    enable_jit: true
    enable_vectorization: true
    batch_size_optimization: true
    memory_pool_size: "1GB"
    thread_pool_size: 8
  
  # Resource limits
  resources:
    max_memory_gb: 2
    max_cpu_cores: 1
    max_disk_gb: 10
    max_network_connections: 1000

# Database Configuration (if using)
database:
  enabled: false
  type: "postgresql"
  host: "postgres"
  port: 5432
  name: "quantum_rerank"
  pool_size: 20
  max_overflow: 30
  pool_timeout: 30
  pool_recycle: 3600
  
  # Connection settings
  connection:
    sslmode: "require"
    connect_timeout: 10
    command_timeout: 60
    application_name: "quantum-rerank-api"

# External Services Configuration
external_services:
  # ML model services
  huggingface:
    enabled: false
    api_timeout: 30
    retry_attempts: 3
    
  # Vector databases
  pinecone:
    enabled: false
    environment: "production"
    
  # Cloud services
  aws:
    enabled: false
    region: "us-west-2"
    
  gcp:
    enabled: false
    project_id: ""
    
  azure:
    enabled: false
    subscription_id: ""

# Feature Flags
features:
  quantum_similarity: true
  classical_fallback: true
  batch_processing: true
  real_time_monitoring: true
  advanced_caching: true
  load_balancing: true
  auto_scaling: true
  
  # Experimental features (disabled in production)
  experimental_algorithms: false
  beta_endpoints: false
  debug_endpoints: false

# Deployment Configuration
deployment:
  environment: "production"
  region: "us-west-2"
  availability_zones: ["us-west-2a", "us-west-2b", "us-west-2c"]
  
  # Kubernetes settings
  kubernetes:
    namespace: "quantum-rerank"
    replicas: 3
    max_replicas: 10
    min_replicas: 3
    
    # Resource requirements
    resources:
      requests:
        cpu: "500m"
        memory: "1Gi"
      limits:
        cpu: "1000m"
        memory: "2Gi"
    
    # Health checks
    health_checks:
      liveness_probe:
        initial_delay: 30
        period: 10
        timeout: 5
        failure_threshold: 3
      
      readiness_probe:
        initial_delay: 5
        period: 5
        timeout: 3
        failure_threshold: 3
    
    # Autoscaling
    autoscaling:
      cpu_target: 70
      memory_target: 80
      scale_up_stabilization: 60
      scale_down_stabilization: 300

# Alerting Configuration
alerting:
  enabled: true
  
  # Alert channels
  channels:
    email:
      enabled: true
      recipients: ["ops@quantumrerank.com", "alerts@quantumrerank.com"]
    
    slack:
      enabled: true
      webhook_url: "${SLACK_WEBHOOK_URL}"
      channel: "#alerts"
    
    pagerduty:
      enabled: true
      integration_key: "${PAGERDUTY_INTEGRATION_KEY}"
  
  # Alert rules
  rules:
    # Performance alerts
    - name: "High Response Time"
      condition: "avg_response_time > 200ms"
      severity: "warning"
      duration: "5m"
      
    - name: "Critical Response Time"
      condition: "avg_response_time > 500ms"
      severity: "critical"
      duration: "2m"
    
    # Error rate alerts
    - name: "High Error Rate"
      condition: "error_rate > 5%"
      severity: "warning"
      duration: "5m"
      
    - name: "Critical Error Rate"
      condition: "error_rate > 10%"
      severity: "critical"
      duration: "2m"
    
    # Resource alerts
    - name: "High Memory Usage"
      condition: "memory_usage > 1.8GB"
      severity: "warning"
      duration: "10m"
      
    - name: "Critical Memory Usage"
      condition: "memory_usage > 2GB"
      severity: "critical"
      duration: "5m"

# Backup and Disaster Recovery
backup:
  enabled: true
  
  # Configuration backup
  config_backup:
    enabled: true
    frequency: "daily"
    retention: 30  # days
    location: "s3://quantum-rerank-backups/config"
  
  # Metrics backup
  metrics_backup:
    enabled: true
    frequency: "hourly"
    retention: 7  # days
    location: "s3://quantum-rerank-backups/metrics"
  
  # Disaster recovery
  disaster_recovery:
    enabled: true
    rto: 60  # minutes
    rpo: 15  # minutes
    backup_regions: ["us-east-1", "eu-west-1"]