# Simple production configuration for QuantumRerank
# Optimized for plug-and-play deployment

quantum_rerank:
  api:
    host: "0.0.0.0"
    port: 8000
    workers: 4
    
  quantum:
    method: "hybrid"
    cache_enabled: true
    n_qubits: 4
    max_circuit_depth: 15
    
  performance:
    max_request_size: "10MB"
    timeout_seconds: 30
    batch_size: 50
    memory_limit_gb: 2.0
    similarity_timeout_ms: 100
    batch_timeout_ms: 500
    
  stability:
    circuit_breaker:
      failure_threshold: 3
      timeout_seconds: 30
      operation_timeout: 15.0
    memory_monitor:
      warning_threshold: 0.8
      critical_threshold: 0.9
      check_interval_seconds: 10
    error_handling:
      include_traceback: false
      rate_limit_retry_after: 60
    
  logging:
    level: "INFO"
    format: "json"
    
  redis:
    url: "${REDIS_URL:-redis://localhost:6379}"
    
  auth:
    api_key: "${QUANTUM_RERANK_API_KEY:-qr-demo-key-change-this}"
    
  security:
    rate_limit: "100/minute"
    cors_enabled: true